=== o-micron/Prototype/PrototypeCommon/assets/scenes/ResourcesSchema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "$id": "ResourcesSchema.json",

  "title": "Resources",
  "description": "A prototype engine resources file",
  "type": "object",
  "properties": {
    "meshes": {
      "description": "the geometries with their corresponding files",
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "type": {
              "description": "the type of the geometry",
              "type": "string"
            },
            "path": {
              "description": "the relative path of the mesh",
              "type": "string"
            }
          }
        }
      ]
    },
    "shaders": {
      "description": "the name of the shaders to be loaded and compiled at startup",
      "type": "array",
      "items": [
        {
          "type": "string"
        }
      ]
    },
    "textures": {
      "description": "the relative path and name of the textures to be loaded at startup",
      "type": "array",
      "items": [
        {
          "type": "string"
        }
      ]
    },
    "materials": {
      "description": "the materials to be created for use in the scene",
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "name": {
              "description": "the unique name of the material",
              "type": "string"
            },
            "shader": {
              "description": "the name of the shader used by the material",
              "type": "string"
            },
            "textures": {
              "description": "the associated textures according to the shader definition (uniform samplers)",
              "type": "array",
              "items": [
                {
                  "description": "the name of the texture",
                  "type": "string"
                }
              ]
            }
          }
        }
      ]
    },
    "framebuffers": {
      "description": "the framebuffers to be created for use in the scene",
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "name": {
              "description": "the unique name of the framebuffer",
              "type": "string"
            },
            "shader": {
              "description": "the unique name of the used shader",
              "type": "string"
            },
            "numColorAttachments": {
              "description": "the number of color attachments used by the framebuffer",
              "type": "number"
            },
            "withDepthAttachment": {
              "description": "if depth attachment is needed",
              "type": "boolean"
            }
          }
        }
      ]
    }
  },
  "required": ["meshes", "shaders", "textures", "materials", "framebuffers"]
}

=== o-micron/Prototype/PrototypeCommon/assets/scenes/Resources_Opengl.json
{
  "framebuffers": [
    {
      "name": "fullscreen",
      "shader": "fullscreen",
      "numColorAttachments": 1,
      "withDepthAttachment": false
    },
    {
      "name": "forward",
      "shader": "forward",
      "numColorAttachments": 1,
      "withDepthAttachment": false
    },
    {
      "name": "deferred",
      "shader": "deferred",
      "numColorAttachments": 5,
      "withDepthAttachment": true
    },
    {
      "name": "gbuffer",
      "shader": "gbuffer",
      "numColorAttachments": 1,
      "withDepthAttachment": false
    },
    {
      "name": "postprocessing",
      "shader": "postprocessing",
      "numColorAttachments": 1,
      "withDepthAttachment": false
    },
    {
      "name": "final",
      "shader": "final",
      "numColorAttachments": 1,
      "withDepthAttachment": false
    }
  ],
  "meshes": [
    {
      "type": "Triangles",
      "path": "capsule.obj"
    },
    {
      "type": "Triangles",
      "path": "cylinder.obj"
    },
    {
      "type": "Triangles",
      "path": "monkey.obj"
    },
    {
      "type": "Triangles",
      "path": "sphere.obj"
    },
    {
      "type": "Triangles",
      "path": "ico.obj"
    }
  ],
  "shaders": [
    "brdf",
    "color",
    "default",
    "deferred",
    "depthMap",
    "final",
    "forward",
    "fullscreen",
    "gbuffer",
    "hdr",
    "irradiance",
    "postprocessing",
    "pbr",
    "prefilter",
    "sky"
  ],
  "textures": [
    "default.jpg",
    "CubeGridTex.png",
    "Metal01/color.jpg",
    "Metal01/normal.jpg",
    "Metal01/metallic.jpg",
    "Metal01/roughness.jpg",
    "Kenny/Dark/texture_08.png",
    "Kenny/Dark/texture_12.png",
    "Kenny/Green/texture_09.png",
    "Kenny/Green/texture_13.png",
    "Kenny/Light/texture_07.png",
    "Kenny/Light/texture_11.png",
    "Kenny/Orange/texture_09.png",
    "Kenny/Orange/texture_13.png",
    "Kenny/Purple/texture_09.png",
    "Kenny/Purple/texture_13.png",
    "Kenny/Red/texture_09.png",
    "Kenny/Red/texture_13.png",
    "icons/play.png",
    "icons/pause.png",
    "icons/reload.png",
    "icons/import.png",
    "icons/export.png",
    "white.png",
    "black.png",
    "airtag/color.png",
    "airtag/metallic.png",
    "airtag/roughness.png",
    "airtag/normal.png",
    "iphone/color.png",
    "iphone/metallic.png",
    "iphone/roughness.png",
    "iphone/normal.png"
  ],
  "materials": [
    {
      "name": "default",
      "shader": "pbr",
      "textures": [
        "default.jpg",
        "Metal01/metallic.jpg",
        "Metal01/normal.jpg",
        "Metal01/roughness.jpg"
      ]
    },
    {
      "name": "Metal01",
      "shader": "pbr",
      "textures": [
        "Metal01/color.jpg",
        "Metal01/metallic.jpg",
        "Metal01/normal.jpg",
        "Metal01/roughness.jpg"
      ]
    },
    {
      "name": "KennyDark",
      "shader": "default",
      "textures": ["Kenny/Dark/texture_08.png", "Kenny/Dark/texture_12.png"]
    },
    {
      "name": "KennyGreen",
      "shader": "default",
      "textures": ["Kenny/Green/texture_09.png", "Kenny/Green/texture_13.png"]
    },
    {
      "name": "KennyLight",
      "shader": "default",
      "textures": ["Kenny/Light/texture_07.png", "Kenny/Light/texture_11.png"]
    },
    {
      "name": "KennyOrange",
      "shader": "default",
      "textures": ["Kenny/Orange/texture_09.png", "Kenny/Orange/texture_13.png"]
    },
    {
      "name": "KennyPurple",
      "shader": "default",
      "textures": ["Kenny/Purple/texture_09.png", "Kenny/Purple/texture_13.png"]
    },
    {
      "name": "KennyRed",
      "shader": "default",
      "textures": ["Kenny/Red/texture_09.png", "Kenny/Red/texture_13.png"]
    },
    {
      "name": "GroundMat",
      "shader": "default",
      "textures": ["CubeGridTex.png", "CubeGridTex.png"]
    },
    {
      "name": "IPhoneMat",
      "shader": "pbr",
      "textures": [
        "iphone/color.png",
        "iphone/metallic.png",
        "iphone/normal.png",
        "iphone/roughness.png"
      ]
    },
    {
      "name": "AirTagMat",
      "shader": "color",
      "textures": ["airtag/color.png"]
    }
  ]
}

=== o-micron/Prototype/PrototypeCommon/assets/scenes/Resources_Vulkan.json
{
  "meshes": [
    {
      "type": "Triangles",
      "path": "capsule.obj"
    },
    {
      "type": "Triangles",
      "path": "cylinder.obj"
    },
    {
      "type": "Triangles",
      "path": "monkey.obj"
    },
    {
      "type": "Triangles",
      "path": "sphere.obj"
    },
    {
      "type": "Triangles",
      "path": "ico.obj"
    }
  ],
  "shaders": ["basic", "default"],
  "textures": [
    "default.jpg",
    "CubeGridTex.png",
    "Metal01/color.jpg",
    "Metal01/normal.jpg",
    "Metal01/metallic.jpg",
    "Metal01/roughness.jpg",
    "Kenny/Dark/texture_08.png",
    "Kenny/Dark/texture_12.png",
    "Kenny/Green/texture_09.png",
    "Kenny/Green/texture_13.png",
    "Kenny/Light/texture_07.png",
    "Kenny/Light/texture_11.png",
    "Kenny/Orange/texture_09.png",
    "Kenny/Orange/texture_13.png",
    "Kenny/Purple/texture_09.png",
    "Kenny/Purple/texture_13.png",
    "Kenny/Red/texture_09.png",
    "Kenny/Red/texture_13.png",
    "icons/play.png",
    "icons/pause.png",
    "icons/reload.png",
    "icons/import.png",
    "icons/export.png",
    "white.png",
    "black.png"
  ],
  "materials": [
    {
      "name": "default",
      "shader": "basic",
      "textures": ["default.jpg"]
    },
    {
      "name": "Monkey",
      "shader": "basic",
      "textures": ["black.png"]
    },
    {
      "name": "Metal01",
      "shader": "basic",
      "textures": ["Metal01/color.jpg"]
    },
    {
      "name": "KennyDark",
      "shader": "default",
      "textures": ["Kenny/Dark/texture_08.png"]
    },
    {
      "name": "KennyGreen",
      "shader": "default",
      "textures": ["Kenny/Green/texture_09.png"]
    },
    {
      "name": "KennyLight",
      "shader": "default",
      "textures": ["Kenny/Light/texture_07.png"]
    },
    {
      "name": "KennyOrange",
      "shader": "default",
      "textures": ["Kenny/Orange/texture_09.png"]
    },
    {
      "name": "KennyPurple",
      "shader": "default",
      "textures": ["Kenny/Purple/texture_09.png"]
    },
    {
      "name": "KennyRed",
      "shader": "default",
      "textures": ["Kenny/Red/texture_09.png"]
    },
    {
      "name": "GroundMat",
      "shader": "default",
      "textures": ["CubeGridTex.png"]
    }
  ],
  "framebuffers": []
}
