=== o-micron/Prototype/PrototypeCommon/assets/scenes/SceneSchema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "$id": "SceneSchema.json",

  "traits": {
    "$id": "traits",
    "Camera": {
      "type": "object",
      "properties": {
        "name": { "type": "string" },
        "fov": { "type": "number" },
        "near": { "type": "number" },
        "far": { "type": "number" },
        "lookSensitivity": { "type": "number" },
        "moveSensitivity": { "type": "number" },
        "position": {
          "type": "array",
          "minItems": 3,
          "maxItems": 3,
          "items": [
            {
              "description": "xyz of the translation",
              "type": "number"
            }
          ]
        },
        "rotation": {
          "type": "array",
          "minItems": 2,
          "maxItems": 2,
          "items": [
            {
              "description": "xy of the euler angles rotation no z rotation ...",
              "type": "number"
            }
          ]
        },
        "orbital": { "type": "boolean" }
      },
      "required": [
        "name",
        "fov",
        "near",
        "far",
        "lookSensitivity",
        "moveSensitivity",
        "position",
        "rotation",
        "orbital"
      ]
    },
    "Collider": {
      "type": "object",
      "properties": {
        "name": { "type": "string" },
        "nameRef": { "type": "string" },
        "shapeType": { "type": "string" },
        "width": { "type": "number" },
        "height": { "type": "number" },
        "depth": { "type": "number" }
      },
      "required": ["name", "nameRef", "shapeType", "width", "height", "depth"]
    },
    "MeshRenderer": {
      "type": "object",
      "properties": {
        "name": { "type": "string" },
        "mesh": { "type": "string" },
        "material": { "type": "string" }
      },
      "required": ["name", "mesh", "material"]
    },
    "Rigidbody": {
      "type": "object",
      "properties": {
        "name": { "type": "string" },
        "linearVelocity": {
          "type": "array",
          "minItems": 3,
          "maxItems": 3,
          "items": [
            {
              "description": "xyz of the linear velocity of the rigidbody",
              "type": "number"
            }
          ]
        },
        "linearDamping": { "type": "number" },
        "angularVelocity": {
          "type": "array",
          "minItems": 3,
          "maxItems": 3,
          "items": [
            {
              "description": "xyz of the angular velocity of the rigidbody",
              "type": "number"
            }
          ]
        },
        "angularDamping": { "type": "number" },
        "mass": { "type": "number" },
        "lockLinearX": { "type": "boolean" },
        "lockLinearY": { "type": "boolean" },
        "lockLinearZ": { "type": "boolean" },
        "lockAngularX": { "type": "boolean" },
        "lockAngularY": { "type": "boolean" },
        "lockAngularZ": { "type": "boolean" },
        "static": { "type": "boolean" },
        "trigger": { "type": "boolean" }
      },
      "required": ["name"]
    },
    "Script": {
      "type": "object",
      "properties": {
        "name": { "type": "string" }
      },
      "required": ["name", "static"]
    },
    "Transform": {
      "type": "object",
      "properties": {
        "name": { "type": "string" },
        "position": {
          "type": "array",
          "minItems": 3,
          "maxItems": 3,
          "items": [
            {
              "description": "xyz of the translation",
              "type": "number"
            }
          ]
        },
        "rotation": {
          "type": "array",
          "minItems": 3,
          "maxItems": 3,
          "items": [
            {
              "description": "xyz of the euler angles rotation",
              "type": "number"
            }
          ]
        },
        "scale": {
          "type": "array",
          "minItems": 3,
          "maxItems": 3,
          "items": [
            {
              "description": "xyz scale",
              "type": "number"
            }
          ]
        }
      },
      "required": ["name", "position", "rotation", "scale"]
    }
  },

  "title": "Scene",
  "description": "A prototype engine scene",
  "type": "object",
  "properties": {
    "name": {
      "description": "The name of the scene",
      "type": "string"
    },
    "bundles": {
      "description": "array of gltf files containing whole scenes",
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "path": {
              "description": "the relative bundle path of the gltf file",
              "type": "string"
            },
            "loaded": {
              "description": "object describing loading process and settings",
              "type": "object",
              "properties": {
                "colliders": {
                  "description": "load physics colliders as 'ColliderShape_ConvexMesh' shapes or 'ColliderShape_TriangleMesh' mesh shapes",
                  "enum": [ "ColliderShape_ConvexMesh", "ColliderShape_TriangleMesh" ]
                },
                "isStatic": {
                  "description": "is it static or dynamic actor",
                  "type": "boolean"
                },
                "isLocked": {
                  "description": "whether to lock linear and angular velocities of the dynamic actor",
                  "type": "boolean"
                }
              }
            }
          }
        }
      ]
    },
    "filters": {
      "description": "The predefined trait system filters",
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "traits": {
              "description": "the associated trait types",
              "type": "array",
              "items": [
                {
                  "type": "string"
                }
              ]
            }
          }
        }
      ]
    },
    "layers": {
      "description": "the unique layers of the scene",
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "name": {
              "description": "the unique name of the layer",
              "type": "string"
            },
            "nodes": {
              "description": "the nodes of the layer",
              "type": "array",
              "items": [
                {
                  "type": "object",
                  "properties": {
                    "name": {
                      "description": "the unique name of the node",
                      "type": "string"
                    },
                    "components": {
                      "description": "the node's attached traits",
                      "type": "array",
                      "uniqueItems": true,
                      "items": [
                        { "$ref": "#traits/Camera" },
                        { "$ref": "#traits/Collider" },
                        { "$ref": "#traits/MeshRenderer" },
                        { "$ref": "#traits/Rigidbody" },
                        { "$ref": "#traits/Script" },
                        { "$ref": "#traits/Transform" }
                      ]
                    },
                    "nodes": {
                      "description": "the child nodes",
                      "type": "array",
                      "items": [
                        {
                          "type": "object"
                        }
                      ]
                    }
                  }
                }
              ]
            }
          }
        }
      ]
    }
  }
}

=== o-micron/Prototype/PrototypeCommon/assets/scenes/AirTags.json
{
  "name": "AirTags",
  "bundles": [
    {
      "path": "iphone/scene.glb"
    },
    {
      "path": "airtag/scene.glb"
    }
  ],
  "filters": [
    {
      "traits": ["Script"]
    },
    {
      "traits": ["Transform", "MeshRenderer"]
    },
    {
      "traits": ["Camera"]
    },
    {
      "traits": ["Transform", "Collider", "Rigidbody"]
    },
    {
      "traits": ["VehicleChasis", "Transform"]
    }
  ],
  "layers": [
    {
      "name": "default",
      "nodes": [
        {
          "name": "MainCamera",
          "components": [
            {
              "name": "Camera",
              "fov": 60.0,
              "near": 0.01,
              "far": 1000.0,
              "lookSensitivity": 0.01,
              "moveSensitivity": 0.1,
              "position": [0.0, 0.0, 7.0],
              "rotation": [0.0, 0.0],
              "orbital": false
            }
          ],
          "nodes": []
        },
        {
          "name": "SceneCamera",
          "components": [
            {
              "name": "Camera",
              "fov": 60.0,
              "near": 0.01,
              "far": 1000.0,
              "lookSensitivity": 0.01,
              "moveSensitivity": 0.1,
              "position": [0.0, 0.0, 7.0],
              "rotation": [0.0, 0.0],
              "orbital": false
            }
          ],
          "nodes": []
        },
        {
          "name": "PaintCamera",
          "components": [
            {
              "name": "Camera",
              "fov": 50.0,
              "near": 0.01,
              "far": 100.0,
              "lookSensitivity": 0.01,
              "moveSensitivity": 0.1,
              "position": [0.0, 0.0, 7.0],
              "rotation": [0.0, 0.0],
              "orbital": true
            }
          ],
          "nodes": []
        },
        {
          "name": "AirTagA",
          "components": [
            {
              "name": "Transform",
              "position": [-1.0, 0.0, -1.0],
              "rotation": [0.0, 0.0, 0.0],
              "scale": [1.0, 1.0, 1.0]
            },
            {
              "name": "MeshRenderer",
              "data": [
                {
                  "mesh": "airtag/scene.glb/AirTag",
                  "material": "AirTagMat"
                }
              ]
            },
            {
              "name": "Collider",
              "nameRef": "airtag/scene.glb/AirTag",
              "shapeType": "ColliderShape_ConvexMesh"
            },
            {
              "name": "Rigidbody",
              "lockLinearX": true,
              "lockLinearY": true,
              "lockLinearZ": true,
              "lockAngularX": true,
              "lockAngularY": true,
              "lockAngularZ": true
            }
          ],
          "nodes": []
        },
        {
          "name": "AirTagB",
          "components": [
            {
              "name": "Transform",
              "position": [0.0, 0.0, -1.0],
              "rotation": [0.0, 0.0, 0.0],
              "scale": [1.0, 1.0, 1.0]
            },
            {
              "name": "MeshRenderer",
              "data": [
                {
                  "mesh": "airtag/scene.glb/AirTag",
                  "material": "AirTagMat"
                }
              ]
            },
            {
              "name": "Collider",
              "nameRef": "airtag/scene.glb/AirTag",
              "shapeType": "ColliderShape_ConvexMesh"
            },
            {
              "name": "Rigidbody",
              "static": true,
              "trigger": true
            }
          ],
          "nodes": []
        },
        {
          "name": "AirTagC",
          "components": [
            {
              "name": "Transform",
              "position": [1.0, 0.0, -1.0],
              "rotation": [0.0, 0.0, 0.0],
              "scale": [1.0, 1.0, 1.0]
            },
            {
              "name": "MeshRenderer",
              "data": [
                {
                  "mesh": "airtag/scene.glb/AirTag",
                  "material": "AirTagMat"
                }
              ]
            },
            {
              "name": "Collider",
              "nameRef": "airtag/scene.glb/AirTag",
              "shapeType": "ColliderShape_ConvexMesh"
            },
            {
              "name": "Rigidbody",
              "lockLinearX": true,
              "lockLinearY": true,
              "lockLinearZ": true,
              "lockAngularX": true,
              "lockAngularY": true,
              "lockAngularZ": true
            }
          ],
          "nodes": []
        },
        {
          "name": "IPhoneA",
          "components": [
            {
              "name": "Transform",
              "position": [0.0, 3.0, -1.0],
              "rotation": [180.0, 90.0, 0.0],
              "scale": [1.0, 1.0, 1.0]
            },
            {
              "name": "MeshRenderer",
              "data": [
                {
                  "mesh": "iphone/scene.glb/iphone",
                  "material": "IPhoneMat"
                }
              ]
            },
            {
              "name": "Collider",
              "nameRef": "iphone/scene.glb/iphone",
              "shapeType": "ColliderShape_ConvexMesh"
            },
            {
              "name": "Rigidbody",
              "lockLinearX": true,
              "lockLinearY": true,
              "lockLinearZ": true,
              "lockAngularX": true,
              "lockAngularY": true,
              "lockAngularZ": true
            }
          ],
          "nodes": []
        }
      ]
    }
  ]
}

=== o-micron/Prototype/PrototypeCommon/assets/scenes/Stalingrad.json
{
  "name": "Stalingrad",
  "bundles": [
    {
      "path": "stalingrad/stalingrad.glb",
      "loaded": {}
    }
  ],
  "filters": [
    {
      "traits": ["Script"]
    },
    {
      "traits": ["Transform", "MeshRenderer"]
    },
    {
      "traits": ["Camera"]
    },
    {
      "traits": ["Transform", "Collider", "Rigidbody"]
    },
    {
      "traits": ["VehicleChasis", "Transform"]
    }
  ],
  "layers": [
    {
      "name": "default",
      "nodes": [
        {
          "name": "MainCamera",
          "components": [
            {
              "name": "Camera",
              "fov": 60.0,
              "near": 1.0,
              "far": 1000.0,
              "lookSensitivity": 0.025,
              "moveSensitivity": 0.25,
              "position": [118.725, 69.022, 63.333],
              "rotation": [-19.65, 56.754],
              "orbital": false
            }
          ],
          "nodes": []
        },
        {
          "name": "SceneCamera",
          "components": [
            {
              "name": "Camera",
              "fov": 60.0,
              "near": 1.0,
              "far": 1000.0,
              "lookSensitivity": 0.025,
              "moveSensitivity": 0.25,
              "position": [118.725, 69.022, 63.333],
              "rotation": [-19.65, 56.754],
              "orbital": false
            }
          ],
          "nodes": []
        },
        {
          "name": "PaintCamera",
          "components": [
            {
              "name": "Camera",
              "fov": 60.0,
              "near": 1.0,
              "far": 1000.0,
              "lookSensitivity": 0.025,
              "moveSensitivity": 0.25,
              "position": [118.725, 69.022, 63.333],
              "rotation": [-19.65, 56.754],
              "orbital": false
            }
          ],
          "nodes": []
        }
      ]
    }
  ]
}

=== o-micron/Prototype/PrototypeCommon/assets/scenes/Raytracing2.json
{
  "name": "Raytracing2",
  "bundles": [],
  "filters": [
    {
      "traits": ["Script"]
    },
    {
      "traits": ["Transform", "MeshRenderer"]
    },
    {
      "traits": ["Camera"]
    },
    {
      "traits": ["Transform", "Collider", "Rigidbody"]
    },
    {
      "traits": ["VehicleChasis", "Transform"]
    }
  ],
  "layers": [
    {
      "name": "hidden",
      "nodes": []
    },
    {
      "name": "default",
      "nodes": [
        {
          "name": "MainCamera",
          "components": [
            {
              "name": "Camera",
              "fov": 60.0,
              "near": 0.01,
              "far": 1000.0,
              "lookSensitivity": 0.025,
              "moveSensitivity": 0.25,
              "position": [0.0, 30.0, 35.0],
              "rotation": [0.0, 0.0],
              "orbital": false
            }
          ],
          "nodes": []
        },
        {
          "name": "SceneCamera",
          "components": [
            {
              "name": "Camera",
              "fov": 60.0,
              "near": 0.01,
              "far": 1000.0,
              "lookSensitivity": 0.025,
              "moveSensitivity": 0.25,
              "position": [0.0, 0.0, 7.0],
              "rotation": [0.0, 0.0],
              "orbital": false
            }
          ],
          "nodes": []
        },
        {
          "name": "PaintCamera",
          "components": [
            {
              "name": "Camera",
              "fov": 50.0,
              "near": 0.01,
              "far": 100.0,
              "lookSensitivity": 0.025,
              "moveSensitivity": 0.25,
              "position": [0.0, 0.0, 7.0],
              "rotation": [0.0, 0.0],
              "orbital": true
            }
          ],
          "nodes": []
        },
        {
          "name": "Ground",
          "components": [
            {
              "name": "Transform",
              "position": [0.0, -1.0, 0.0],
              "rotation": [0.0, 0.0, 0.0],
              "scale": [400.0, 1.0, 400.0]
            },
            {
              "name": "MeshRenderer",
              "data": [
                {
                  "mesh": "CUBE",
                  "material": "default"
                }
              ]
            },
            {
              "name": "Collider",
              "nameRef": "CUBE",
              "shapeType": "ColliderShape_Box",
              "width": 1.0,
              "height": 1.0,
              "depth": 1.0
            },
            {
              "name": "Rigidbody",
              "static": true
            }
          ],
          "nodes": []
        },
        {
          "name": "C",
          "components": [
            {
              "name": "Transform",
              "position": [10.0, 5.0, 0.0],
              "rotation": [0.0, 0.0, 0.0],
              "scale": [1.0, 1.0, 1.0]
            },
            {
              "name": "MeshRenderer",
              "data": [
                {
                  "mesh": "sphere.obj",
                  "material": "default"
                }
              ]
            },
            {
              "name": "Collider",
              "nameRef": "sphere.obj",
              "shapeType": "ColliderShape_Sphere",
              "radius": 1.0
            },
            {
              "name": "Rigidbody"
            }
          ],
          "nodes": []
        },
        {
          "name": "D",
          "components": [
            {
              "name": "Transform",
              "position": [-10.0, 10.0, -5.0],
              "rotation": [0.0, 0.0, 0.0],
              "scale": [1.0, 1.0, 1.0]
            },
            {
              "name": "MeshRenderer",
              "data": [
                {
                  "mesh": "CUBE",
                  "material": "default"
                }
              ]
            },
            {
              "name": "Collider",
              "nameRef": "CUBE",
              "shapeType": "ColliderShape_Box",
              "width": 1.0,
              "height": 1.0,
              "depth": 1.0
            },
            {
              "name": "Rigidbody"
            }
          ],
          "nodes": []
        },
        {
          "name": "E",
          "components": [
            {
              "name": "Transform",
              "position": [10.0, 15.0, 0.0],
              "rotation": [0.0, 0.0, 0.0],
              "scale": [1.0, 1.0, 1.0]
            },
            {
              "name": "MeshRenderer",
              "data": [
                {
                  "mesh": "ico.obj",
                  "material": "default"
                }
              ]
            },
            {
              "name": "Collider",
              "nameRef": "ico.obj",
              "shapeType": "ColliderShape_ConvexMesh",
              "width": 1.0,
              "height": 1.0,
              "depth": 1.0
            },
            {
              "name": "Rigidbody"
            }
          ],
          "nodes": []
        },
        {
          "name": "S0",
          "components": [
            {
              "name": "Transform",
              "position": [-15.0, 15.0, -10.0],
              "rotation": [0.0, 0.0, 0.0],
              "scale": [1.0, 1.0, 1.0]
            },
            {
              "name": "MeshRenderer",
              "data": [
                {
                  "mesh": "monkey.obj",
                  "material": "default"
                }
              ]
            },
            {
              "name": "Collider",
              "nameRef": "monkey.obj",
              "shapeType": "ColliderShape_ConvexMesh",
              "width": 1.0,
              "height": 1.0,
              "depth": 1.0
            },
            {
              "name": "Rigidbody"
            }
          ],
          "nodes": []
        }
      ]
    }
  ]
}

=== o-micron/Prototype/PrototypeCommon/assets/scenes/Cloth.json
{
  "name": "Cloth",
  "bundles": [
    {
      "path": "cloth/cloth.gltf",
      "loaded": {
        "colliders": "ColliderShape_ConvexMesh",
        "isStatic": true
      }
    }
  ],
  "filters": [
    {
      "traits": ["Script"]
    },
    {
      "traits": ["Transform", "MeshRenderer"]
    },
    {
      "traits": ["Camera"]
    },
    {
      "traits": ["Transform", "Collider", "Rigidbody"]
    },
    {
      "traits": ["VehicleChasis", "Transform"]
    }
  ],
  "layers": [
    {
      "name": "default",
      "nodes": [
        {
          "name": "MainCamera",
          "components": [
            {
              "name": "Camera",
              "fov": 60.0,
              "near": 0.01,
              "far": 1000.0,
              "lookSensitivity": 0.025,
              "moveSensitivity": 0.25,
              "position": [0.0, 0.0, 7.0],
              "rotation": [0.0, 0.0],
              "orbital": false
            }
          ],
          "nodes": []
        },
        {
          "name": "SceneCamera",
          "components": [
            {
              "name": "Camera",
              "fov": 60.0,
              "near": 0.01,
              "far": 1000.0,
              "lookSensitivity": 0.025,
              "moveSensitivity": 0.25,
              "position": [0.0, 0.0, 7.0],
              "rotation": [0.0, 0.0],
              "orbital": false
            }
          ],
          "nodes": []
        },
        {
          "name": "PaintCamera",
          "components": [
            {
              "name": "Camera",
              "fov": 50.0,
              "near": 0.01,
              "far": 100.0,
              "lookSensitivity": 0.025,
              "moveSensitivity": 0.25,
              "position": [0.0, 0.0, 7.0],
              "rotation": [0.0, 0.0],
              "orbital": true
            }
          ],
          "nodes": []
        },
        {
          "name": "Ground",
          "components": [
            {
              "name": "Transform",
              "position": [0.0, -15.0, 0.0],
              "rotation": [0.0, 0.0, 0.0],
              "scale": [100.0, 1.0, 100.0]
            },
            {
              "name": "MeshRenderer",
              "data": [
                {
                  "mesh": "CUBE",
                  "material": "default"
                }
              ]
            },
            {
              "name": "Collider",
              "nameRef": "CUBE",
              "shapeType": "ColliderShape_Box",
              "width": 1.0,
              "height": 1.0,
              "depth": 1.0
            },
            {
              "name": "Rigidbody",
              "static": true
            }
          ],
          "nodes": []
        }
      ]
    }
  ]
}
